import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DrawerAppBar from "@/components/DrawerAppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DrawerAppBar />
        {children}
      </body>
    </html>
  );
}
